# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rill < Formula
  desc "The Rill CLI"
  homepage "https://github.com/rilldata/rill"
  version "0.48.6"
  license "Apache 2.0"

  on_macos do
    on_intel do
      url "https://cdn.rilldata.com/rill/v0.48.6/rill_darwin_amd64.zip"
      sha256 "d7ad66ca17efad68f61a209e86f7be80487740dde4dfa717c17963b87089543d"

      def install
        bin.install "rill"
      end
    end
    on_arm do
      url "https://cdn.rilldata.com/rill/v0.48.6/rill_darwin_arm64.zip"
      sha256 "39a288cbcbba7a4bf91d4d3e4c23f3dc8d6c681fba272bf9a8bcd5b406475abf"

      def install
        bin.install "rill"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://cdn.rilldata.com/rill/v0.48.6/rill_linux_amd64.zip"
        sha256 "ba649567b9ca9d3c60854724bc5afc0c98722bf34a20555c2e7cc44126be4202"

        def install
          bin.install "rill"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://cdn.rilldata.com/rill/v0.48.6/rill_linux_arm64.zip"
        sha256 "f8c5e35c412abdf7bfd3a6d7a7184bae64ab09eecb238d1f292045a8199a1def"

        def install
          bin.install "rill"
        end
      end
    end
  end

  test do
    system "#{bin}/rill --version"
  end
end
