# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rill < Formula
  desc "The Rill CLI"
  homepage "https://github.com/rilldata/rill-developer"
  version "0.0.0-test3"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://cdn.rilldata.com/rill/v0.0.0-test3/rill_darwin_arm64.zip"
      sha256 "e9dd2ad871727094d24ba73059de06c56730fea80a63f54377eb4be20e5e486f"

      def install
        bin.install "rill"
      end
    end
    if Hardware::CPU.intel?
      url "https://cdn.rilldata.com/rill/v0.0.0-test3/rill_darwin_amd64.zip"
      sha256 "a34305e8ba38a55bac1fabc6a9c45d0029102f83f1df8c3497cb969642b6aea9"

      def install
        bin.install "rill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://cdn.rilldata.com/rill/v0.0.0-test3/rill_linux_amd64.zip"
      sha256 "ccc84c07a4fc5bc0853c697d232ccd8347ac8859cb9877df8f2509d7875aeec4"

      def install
        bin.install "rill"
      end
    end
  end

  test do
    system "#{bin}/rill --version"
  end
end
