# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rill < Formula
  desc "The Rill CLI"
  homepage "https://github.com/rilldata/rill"
  version "0.42.2"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://cdn.rilldata.com/rill/v0.42.2/rill_darwin_arm64.zip"
      sha256 "cc91d1ca11374a0c5cc805ce9768de6ce5d6ce444797617875f1a2b97c0142de"

      def install
        bin.install "rill"
      end
    end
    if Hardware::CPU.intel?
      url "https://cdn.rilldata.com/rill/v0.42.2/rill_darwin_amd64.zip"
      sha256 "9bdacdba39b6c9ea558d62144e75b7af35916d3c384def33537ba25187ea2a8a"

      def install
        bin.install "rill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://cdn.rilldata.com/rill/v0.42.2/rill_linux_amd64.zip"
      sha256 "3b74303418e8f5dcc0df6371e3a693e8c6586ec42ca19aacc77c3091c4f6d458"

      def install
        bin.install "rill"
      end
    end
  end

  test do
    system "#{bin}/rill --version"
  end
end
